// models/Checklist.ts
import { ObjectId } from 'mongoose';
export interface Question {
  question: string;
  answer: string;
  explanation?: string;
}

export interface IChecklist {
  orderId: string;
  userId: ObjectId;
  questions: Question[];
  createdAt?: string; // Optional, will be auto-generated by MongoDB
  updatedAt?: string; // Optional, will be auto-generated by MongoDB
}
